In [1]:
import tensorflow as tf

In [2]:
embeddings_0d = tf.constant([17, 22, 35, 51])

In [3]:
embeddings_4d = tf.constant([[1, 0, 0, 0],
                             [0, 1, 0, 0],
                             [0, 0, 1, 0],
                             [0, 0, 0, 1]])


In [4]:
embeddings_2x2d = tf.constant([[[1, 0], [0, 0]],
                               [[0, 1], [0, 0]],
                               [[0, 0], [1, 0]],
                               [[0, 0], [0, 1]]])


In [5]:
ids = tf.constant([1, 0, 2])

In [6]:
lookup_0d = tf.nn.embedding_lookup(embeddings_0d, ids)
print(lookup_0d)

lookup_4d = tf.nn.embedding_lookup(embeddings_4d, ids)
print(lookup_4d)

lookup_2x2d = tf.nn.embedding_lookup(embeddings_2x2d, ids)
print(lookup_2x2d)

tf.Tensor([22 17 35], shape=(3,), dtype=int32)
tf.Tensor(
[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[0 1]
  [0 0]]

 [[1 0]
  [0 0]]

 [[0 0]
  [1 0]]], shape=(3, 2, 2), dtype=int32)
